---
    - name: Get list of containers
      command: lxc-ls -f | awk 'NR > 1 {print $1}'
      become: true
      register: containers

    - name: Print container List
      debug:
        msg: "{{ containers.stdout_lines }}"

    - name: Start each container
      shell: lxc-start -n "{{ item }}"
      with_items: "{{ containers.stdout_lines }}"
      become: true


    - name: List out the containers state
      shell: lxc-ls --fancy
      become: true
      register: container_state

    - name: Print out the container state in display
      debug:
        var: container_state.stdout_lines
