---
    - name: Get list of containers
      shell: lxc-ls -f | awk 'NR > 1 {print $1}'
      register: containers

    - name: Start each container
      shell: lxc-start -n "{{ item }}"
      with_items: "{{ containers.stdout_lines }}"

    - name: List out the containers state
      shell: lxc-ls -fancy
      register: container_state

    - name: Print out the container state in display
      debug:
        msg: "{{ container_state.stdout_lines }}"
