---
    - name: Get list of containers
      shell: lxc-ls -f | awk 'NR > 1 {print $1}'
      register: containers

    - name: stop each container
      shell: lxc-stop -n "{{ item }}"
      with_items: "{{ containers.stdout_lines }}"

    - name: List out the containers state
      shell: lxc-ls --fancy
      register: container_state

    - name: Print out the container state in display
      debug:
        var: container_state.stdout_lines
